### ISSUE TITLE
Incorrectly description in F119 砲熕兵装の整備

### ISSUE THREAD

**Issue by lawvs** [antest1/kcanotify-gamedata#10]
Downstream https://github.com/lawvs/poi-plugin-quest-2/issues/106

The quest `F119 砲熕兵装の整備` improperly used `Cy11/C78`'s quest description.

Error data in scn:

https://github.com/antest1/kcanotify-gamedata/blob/29e2a8933c5a925e94dfc5a7444d8f9681a516aa/files/quests-scn.json#L3806-L3812

Error data in tcn:

https://github.com/antest1/kcanotify-gamedata/blob/29e2a8933c5a925e94dfc5a7444d8f9681a516aa/files/quests-tcn.json#L3806-L3812

---

The data of KC3 translations did not find this error.

https://github.com/KC3Kai/kc3-translations/blob/de3338a5cb1a74609c949df6f55622269cb05f9e/data/scn/quests.json#L3093-L3097

```json
  "1131": {
    "name": "炮熕兵装的整备",
    "desc": "废弃小口径主炮×18、中口径主炮×12、暴雷系装备×6。准备应急修理要员×1、弹药2500、钢材3000。（任务完成后，准备的资源等会被消耗）",
    "memo": "➣奖励：\n¶选择1：12.7cm连装炮B型改二×3 或 12.7cm连装高角炮(后期型)×2 或 新型火炮兵装资材×1\n¶选择2：14cm连装炮改★+3 或 15.2cm连装炮改★+2 或 20.3cm(2号)连装炮×2"
  },
```

https://github.com/antest1/kcanotify-gamedata/blob/29e2a8933c5a925e94dfc5a7444d8f9681a516aa/files/quests-scn.json#L2680-L2687

**Comment by antest1** [comment]
fixed in 8260ae1, thanks for the report!
