### ISSUE TITLE
Unexpected token NaN in quests-*.json

### ISSUE THREAD

**Issue by lawvs** [antest1/kcanotify-gamedata#11]
SyntaxError: Unexpected token 'N', ..."rewards": NaN, "reso"... is not valid JSON

https://github.com/antest1/kcanotify-gamedata/blob/53d4035985e9d094ad6aefedd20e0a0a517e32cd/files/quests-en.json#L4334

Blamed to https://github.com/antest1/kcanotify-gamedata/commit/1d1bb8171fb7d237d5f8098c61a81a50fd051e4a#diff-89fb41982ea5dba3be56be9e491de381f4aec19d6d185d6a31fb82cf69b0cb13L4260

**Comment by antest1** [comment]
sorry for checking this issue late! I updated the checking script so I hope it will not happen again.
also since I don't check github issue that often so if there are any problem in kcanotify-gamedata, please send mail to me instead!
(kcanotify [at] gmail.com)
