### ISSUE TITLE
Chinese translation source requests

### ISSUE THREAD

**Issue by TrickLin** [antest1/kcanotify-gamedata#4]
Dear kcanotify development team,

I am a maintenance team member for kcwiki（zh.kcwiki.cn）, a Chinese wiki for KanColle. I was impressed by the quality of your simplified Chinese mission descriptions. May I know your source and how you grab the texts? I am curious about your methods. Do you grab them by hand or by script? If it is by script, could you please show me the code? It will be very appreciated.

Thank you very much!

Sincerely,
TrickLin

**Comment by antest1** [comment]
Hi TrickLin,

I basically worked with the help of volunteer translator for scn/tcn translations, and use text from kcwiki when they are busy. 
I usually grab text and fix from kc3-translation repo by hand when working with other languages.

Thanks,
antest1
