### ISSUE TITLE
Mission requirement items statistics

### ISSUE THREAD

**Issue by skysumbra** [antest1/kcanotify-gamedata#5]
Hi antest1
From quests-tcn.json file, could i refer to example if i want to add other mission requirement item statistics?
thank you
```
	"214": {
		"code": "Bw1",
		"name": "(週任) あ號作戰",
		"desc": "一周內全力出擊，儘可能多地捕捉敵艦隊，迎擊他們",
		"memo": "出擊36次, 和敵軍頭目交戰24次, 擊敗敵軍頭目12次, 勝利S 6次。",
		"unlock": [221],
		"tracking": [
			[0, 36],
			[0, 24],
			[0, 12],
			[0, 6]
		]
	},
```

**Comment by antest1** [comment]
Hi skysumbra,

if you mean the format of `memo` field, there is no fixed format so you can do it whatever you want~
as kcanotify combines multiple lines into single line so just don't put newline character on text.

we also don't use `unlock` and `tracking` field in kcanotify (there are from [kc3-translations](https://github.com/KC3Kai/kc3-translations)) so you need not to consider about them.

**Comment by skysumbra** [comment]
Is it possible add some **tracking** field for old mission ?
What's easy method let some old mission have item statistics tip ?
And i find **quest_track.json** file in App folder, is file check item statistics?
May i edit these file and run test  locally ?
So sorry, i have some questions, thank you.

**Comment by antest1** [comment]
1. you can add tracking info but they are not used in the kcanotify app.
2. I think there is no easy way for doing that, as it was not designed to support those info at the beginning orz
3. `quest_track.json` file is for quest progress tracking feature in kcanotify, which is not updated for a while so I think they will not work for many recent quests, you can still test it locally.
