### ISSUE TITLE
New quest fomat

### ISSUE THREAD

**Issue by lawvs** [antest1/kcanotify-gamedata#9]
I found there are format changes in https://github.com/antest1/kcanotify-gamedata/commit/9369ce3da64080883deec996b3ffed3cbbdfa2a6

In order to make the poi-plugin-quest-2 compatible with the new data, I need to update the data parsing. Related to https://github.com/lawvs/poi-plugin-quest-2/pull/55

Can you explain the meaning of the second array of the `resource`?

**Comment by antest1** [comment]
`resources` is the reward for quest clear.
format: `[[燃料,弾薬,鋼材,ボーキサイト], [高速修復材,高速建造材,開発資材,改修資材]]`

**Comment by lawvs** [comment]
Thank you very much for your detailed explanation.
